### ISSUE TITLE
gamClustering Error: Trying to fix variable with value that is out of possible range.

### ISSUE THREAD

**Issue by jujurring** [ctlab/GAMclust#2]
Hi,
Thank you for providing your tools. But i'm got some issues.

When I run gamClustering function, it threw this error :

```
# GAM-clustering analysis
results <- gamClustering(E.prep = matrix.prep,
                         network.prep = network.prep,
                         cur.centers = cur.centers,                     
                         start.base = 0.5,
                         base.dec = 0.05,
                         max.module.size = 50,                         
                         cor.threshold = 0.7,
                         p.adj.val.threshold = 0.05,                         
                         batch.solver = seq_batch_solver(solver),
                         work.dir = work.dir,                         
                         show.intermediate.clustering = FALSE,
                         verbose = FALSE,
                         collect.stats = TRUE)



[*] Iteration 1
[*] Iteration 2
Max cor exceeded 0.7: 0.75
[*] Iteration 3
[*] Iteration 4
[*] Iteration 5
[*] Iteration 6
[*] Iteration 7
[*] Iteration 8
[*] Iteration 9
[*] Iteration 10
[*] Iteration 11
[*] Iteration 12
[*] Iteration 13
[*] Iteration 14
[*] Iteration 15
[*] Iteration 16
[*] Iteration 17
[*] Iteration 18
[*] Iteration 19
[*] Iteration 20
[*] Iteration 21
[*] Iteration 22
[*] Iteration 23
[*] Iteration 24
[*] Iteration 25
Error: Trying to fix variable with value that is out of possible range.

```

I modulated many options  in this function like max.module.size , cor.threshold and p.adj value. 
Could you tell me how can I solve this problem?

**Comment by anastasiiaNG** [comment]
Hi, @jujurring.

Could you please provide the data object `matrix.prep` as well as specify which tutorial (bulk/sc/spat) and solver did you use? Thus I could reproduce your error in my hands. Thank you.

Best,
Ana

**Comment by jujurring** [comment]
Hi, Ana. 
Thank you for your reply.

I ran the tutorial of sc version and  used the solver produced by `solver <- mwcsr::rnc_solver()`. 
My data object `matrix prep `is tabula muris senis data in  your vignette. Thank you. 

Best regards,
jujurring

**Comment by assaron** [comment]
@jujurring We've fixed a bug in the solver. If you can reinstall `mwcsr` package from github with `devtools::install_github("ctlab/mwcsr")` the error should be gone.

**Comment by jujurring** [comment]
Thank you for your reply. 
I succeeded in getting the result of `gamClustering` function. 

Thank you so much :)
